config-test: this is default

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

education:
  rabbit:
    receiveQ: education_homework_result_created