config-test: this is default

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  data-source:
    url: jdbc:mysql://localhost:3308/homework_result_query
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

education:
  rabbit:
    publishX: education_homework_result_event
    receiveQ: education_homework_result_created